# Site settings
title: Tinypint - A Web Design & Marketing Agency in Grand Rapids
email: bob@tinypint.com
description: > # this means to ignore newlines until "baseurl:"
  We make, market & maintain WordPress websites, web-based applications and interactive marketing campaigns. Need a hand? Give us a call today at 616.536.8283 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tinypint.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
